shared:
  image: node:20
jobs:
  zero:
    requires: [~pr]
    steps:
      - echo: echo zero
  first:
    requires: [~pr, ~commit]
    steps:
      - echo: echo first
  second:
    requires:
      - first
      - sd@2052:component
      - sd@2053:component
      - sd@2054:component
    steps:
      - echo: echo second
  third:
    requires:
      - second
      - sd@2052:first
      - sd@2052:second
      - sd@2052:third
      - sd@2053:first
      - sd@2053:second
      - sd@2053:third
      - sd@2054:first
      - sd@2054:second
      - sd@2054:third
    steps:
      - echo: echo third
